services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "database-password"
    volumes:
      - mysql_data:/var/lib/mysql

  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile_prod

    image: "maacke16/microblog:1.0.0-prod"
    container_name: microblog
    depends_on:
      - mysql
    ports:
      - "8000:5000"
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: "mysql+pymysql://microblog:database-password@mysql/microblog"

volumes:
  mysql_data:
