global:
  scrape_interval: 5s # minst 30

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  
  - job_name: "flask"
    static_configs:
      - targets: ["prod:5000"] # Ã„ndra till vm  ip
        labels:
          instance: flask