---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-MAPG23-DV1673-H25-LP2 # Change me
domain_name: mapg23.me # Change me

admin_email: mapg23@student.bth.se

vmtags:
  StudentId: mapg23 # Change me

pub_ssh_key_location: "/home/marcus/.ssh/azure_key.pub" # Change me, your local ssh key!

server_user: "deploy"
server_user_pass: "password" # change me
server_user_groups:
  - sudo
