---
sg_groups:
  - name: loadbalancer
    port_rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1002
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 1003
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
  - name: appserver
    port_rules:
      - name: APP
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      - name: HTTP
        protocol: Tcp
        destination_port_range: 5000
        access: Allow
        priority: 1002
        direction: Inbound
        source_address_prefix: "{{ hostvars['localhost']['groups']['loadbalancer'][0] }}"
        # source_address_prefix: "0.0.0.0" # Ändra till loadbalancer

  - name: database
    port_rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"

      - name: MYSQL-APP1
        protocol: Tcp
        destination_port_range: 3306
        access: Allow
        priority: 1002
        direction: Inbound
        source_address_prefix: "{{ hostvars['localhost']['groups']['appserver'][0] }}/32" # Ändra till appserver 0

      - name: MYSQL-APP2
        protocol: Tcp
        destination_port_range: 3306
        access: Allow
        priority: 1003
        direction: Inbound
        source_address_prefix: "{{ hostvars['localhost']['groups']['appserver'][1] }}/32" # Ändra till appserver 0
        # source_address_prefix: "0.0.0.0/32" # Ändra till appserver 1

  - name: monitoring
    port_rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"

      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1002
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 1003
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      
      - name: Grafana
        protocol: Tcp
        destination_port_range: 3000
        access: Allow
        priority: 1004
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"
      

      - name: Prometheus
        protocol: Tcp
        destination_port_range: 9090
        access: Allow
        priority: 1005
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"

      - name: NodeExporter
        protocol: Tcp
        destination_port_range: 9100
        access: Allow
        priority: 1006
        direction: Inbound
        source_address_prefix: "0.0.0.0/0"