apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: maacke16/microblog:14.0.13-prod
        imagePullPolicy: Always
        name: microblog
        ports:
          - containerPort: 5000
        

        env:
          - name: SECRET_KEY
            value: "my-secret-key"

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: DB_PASSWORD


          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: DB_URL

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10

        resources:
          requests: # min
            cpu: "250m"
          limits: # max
            cpu: "500m"