apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microblog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microblog
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20