apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microblog
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx # kopplar vår ingress till den installerade nginx-ingress
  tls: # sätter att vi ska bara acceptera https trafik till er domän
  - hosts:
    - kubernetes.mapg23.me
    secretName: demo-tls # det kommer senare skapas en secret med detta namnet som innehåller certificatet för vårt domännamn.
  rules:
  - host: kubernetes.mapg23.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microblog
            port:
              number: 80