name: Deployment

on:
  release:
    types:
      - published

jobs:
  deploy-tests:
    uses: ./.github/workflows/python-app.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [deploy-tests]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod -f docker/Dockerfile_prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod

      - name: Install pip
        run: sudo apt-get install -y python3-pip

      - name: Install setuptools
        run: sudo apt-get install -y python3-setuptools

      - name: Install Azure
        run: |
          pip install azure-cli azure-mgmt-compute azure-mgmt-resource azure-identity azure-mgmt-network

      - name: install Azure fallback
        run: |
          pip install ansible[azure]

      - name: Install Ansible
        run: pip install "ansible>=10.0.0,<11.0.0"

      - name: Install Ansible Galaxy roles/collections
        working-directory: ansible
        run: |
          if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml; fi

      - name: Run Ansible site.yml
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
          ansible-playbook \
            -i hosts site.yml \
            -e "ansible_python_interpreter=/usr/bin/python3" \
            -e "release_tag=${{ github.event.release.tag_name }}"
