name: Deployment

on:
  release:
    types:
      - published

jobs:
  deploy-tests:
    uses: ./.github/workflows/python-app.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [deploy-tests]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod -f docker/Dockerfile_prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod

      - name: Set up Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install "ansible[azure]>=10.0.0,<11.0.0"
          pip install ansible[azure] azure-cli azure-mgmt-resource azure-mgmt-compute azure-mgmt-network azure-mgmt-dns azure-identity azure-mgmt-storage azure-mgmt-sql

        shell: bash

      - name: Install Ansible Galaxy roles/collections
        working-directory: ansible
        run: |
          source ../venv/bin/activate
          if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml; fi
        shell: bash

      - name: Check Azure CLI installed
        run: |
          source venv/bin/activate
          pip list
          which python
          python -c "import azure.cli"

      - name: Run Ansible site.yml
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
          source ../venv/bin/activate
          ansible-playbook \
            -i hosts site.yml \
            -e "ansible_python_interpreter=../venv/bin/python3" \
            -e "release_tag=${{ github.event.release.tag_name }}"
        shell: bash
