name: Deployment

on:
  release:
    types:
      - published

jobs:
  deploy-tests:
    uses: ./.github/workflows/python-app.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [deploy-tests]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod -f docker/Dockerfile_prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/microblog:${{ github.event.release.tag_name }}-prod

      - name: Set up Python virtualenv and install Azure dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install "ansible[azure]>=10.0.0,<11.0.0"
          curl -sSL https://raw.githubusercontent.com/ansible-collections/azure/36d034034bbc9bb1e83007d2a643d4a1af2f8776/requirements.txt -o azure-requirements.txt
          pip install -r azure-requirements.txt
        shell: bash

      - name: Install Ansible Galaxy roles/collections
        working-directory: ansible
        run: |
          source ../venv/bin/activate
          if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml; fi
        shell: bash

      - name: Check Azure CLI installed
        run: |
          source venv/bin/activate
          pip list
          which python
          python -c "import azure.cli"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible deploy.yml
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
        run: |
          ansible-playbook \
            -i hosts rolling_update.yml \
            -e "ansible_python_interpreter=/usr/bin/python3" \
            -e "release_tag=${{ github.event.release.tag_name }}"
        shell: bash
